### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by yuppx** [MILU-YOU/Price-prediction#1]
请问哪里可以下载数据呢

**Comment by MILU-YOU** [comment]
数据我一并上传到了GitHub上啊，本仓库的第四个文件夹就是

**Comment by yuppx** [comment]
我下载不到😭 您有其他的下载链接吗

**Comment by MILU-YOU** [comment]
链接：https://pan.baidu.com/s/17bOGEBIlgoSwEsK0i1nu0A 
提取码：2586

**Comment by MILU-YOU** [comment]
因为数据文件比较大，应该是我上传的时候出了问题。你可以通过上面的云盘链接下载该项目的原始数据。

**Comment by yuppx** [comment]
哇，好的好的，谢谢谢谢
